pipeline {
    agent any
  
    stages{
        stage('database container') {
            steps {
                
                sh 'echo database container already running'
             }
          }
        stage('Docker build') {
            steps {
                sh 'cd LMS-BE && sudo docker build -t backend .'
            }
          }
        stage('Docker container') {
            steps {
                sh 'sudo docker container run -dt --name be -p 9090:8080 backend'
            }
        }
        stage('Docker') {
            steps {
                sh 'echo deployment done'
               }
          }
    }
}
