pipeline {
    agent any
    
    stages {
        stage('Sonarqube analysis') {
            steps {
                // Maven clean and verify
                script {
                    sh 'cd LMS-BE/ && mvn clean verify sonar:sonar ' +
                       '-Dsonar.projectKey=lms-java ' +
                       "-Dsonar.projectName='lms-java' " +
                       '-Dsonar.host.url=http://54.152.141.60:9000 ' +
                       '-Dsonar.token=sqp_936474d0e8493d4885e019a44471c54c07c2f33b ' +
                       "-DskipTests"
                }
            }
        }
    }
    
    post {
        always {
            // Email notification with log file attachment and compressLog=true
            emailext body: "project: ${env.JOB_NAME} \n build number: ${env.BUILD_NUMBER} \n URL: ${env.BUILD_URL}", 
                      subject: "${currentBuild.result}: SonarQube Analysis Notification", 
                      to: "chetan1993k@gmail.com, muralialakuntla3@gmail.com, sathishgodavarthi@gmail.com",
                      attachLog: true,
                      compressLog: true
        }
    }
}
